In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import networkx as nx
import csv
import numpy as np
import sklearn
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Constructing Function

In [ ]:
dor_income_2010 = pd.read_excel('/content/drive/MyDrive/DS project/Dorchester_income/ACSST5Y2010.xlsx', sheet_name=1, header=None)
dor_income_2020 = pd.read_excel('/content/drive/MyDrive/DS project/Dorchester_income/ACSST5Y2020.xlsx', sheet_name=1, header=None)

In [ ]:
dor_income_2010

,0,1,2,3,4,5,6,7,8,9,...,223,224,225,226,227,228,229,230,231,232
0,NaN,"Census Tract 901, Suffolk County, Massachusetts",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Census Tract 902, Suffolk County, Massachusetts",...,NaN,NaN,"Census Tract 1008, Suffolk County, Massachusetts",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Households,NaN,Families,NaN,Married-couple families,NaN,Nonfamily households,NaN,Households,...,Nonfamily households,NaN,Households,NaN,Families,NaN,Married-couple families,NaN,Nonfamily households,NaN
2,Label,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,...,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error
3,Total,"1,709",±114,"1,129",±141,420,±113,580,±115,706,...,813,±137,"2,376",±149,"1,363",±171,786,±175,"1,013",±208
4,"Less than $10,000",14.7%,±6.4,8.0%,±5.9,6.2%,±9.8,27.8%,±13.4,18.3%,...,15.1%,±8.7,13.3%,±5.9,5.9%,±6.1,2.0%,±3.1,23.3%,±9.9
5,"$10,000 to $14,999",4.4%,±2.9,7.0%,±4.5,6.9%,±7.1,1.4%,±2.5,27.9%,...,13.4%,±7.2,3.8%,±3.0,2.6%,±2.9,1.5%,±3.1,5.3%,±6.7
6,"$15,000 to $24,999",22.6%,±7.5,19.0%,±7.9,12.6%,±11.3,32.6%,±16.2,22.4%,...,14.5%,±6.2,11.2%,±5.5,4.8%,±4.1,5.2%,±5.0,19.7%,±10.9
7,"$25,000 to $34,999",14.8%,±6.2,17.6%,±7.7,26.2%,±15.0,14.1%,±9.8,4.5%,...,6.6%,±4.1,4.8%,±3.0,7.3%,±6.0,3.2%,±3.9,4.7%,±4.2
8,"$35,000 to $49,999",12.2%,±5.4,16.0%,±7.5,7.1%,±6.5,0.0%,±6.3,8.4%,...,8.2%,±5.3,11.9%,±5.8,6.1%,±4.6,3.7%,±4.6,20.9%,±11.5
9,"$50,000 to $74,999",15.2%,±6.3,14.7%,±7.4,13.6%,±12.2,15.2%,±10.6,10.1%,...,25.2%,±10.1,19.6%,±6.0,26.3%,±7.8,28.9%,±8.9,7.8%,±5.4
10,"$75,000 to $99,999",9.5%,±4.4,9.7%,±5.3,14.8%,±10.1,9.0%,±8.7,4.0%,...,5.0%,±4.1,10.0%,±5.2,10.4%,±6.2,11.7%,±7.4,9.5%,±8.6
11,"$100,000 to $149,999",4.7%,±3.1,6.0%,±4.3,9.0%,±9.4,0.0%,±6.3,1.6%,...,11.8%,±8.6,16.6%,±6.0,23.6%,±9.3,21.2%,±10.2,7.1%,±6.0
12,"$150,000 to $199,999",1.8%,±1.9,1.9%,±2.4,3.6%,±5.6,0.0%,±6.3,3.0%,...,0.0%,±4.5,8.8%,±5.2,13.0%,±8.7,22.5%,±13.4,1.6%,±2.6
13,"$200,000 or more",0.0%,±2.2,0.0%,±3.3,0.0%,±8.5,0.0%,±6.3,0.0%,...,0.0%,±4.5,0.0%,±1.6,0.0%,±2.7,0.0%,±4.7,0.0%,±3.6
14,Median income (dollars),"30,389","±6,598","33,844","±9,138","34,500","±17,298","20,617","±6,050","16,055",...,"35,625","±18,161","56,800","±15,463","74,007","±17,425","84,787","±23,253","26,964","±22,092"
15,Mean income (dollars),"41,281","±5,793","45,496","±7,031",N,N,"27,319","±6,365","31,323",...,"47,412","±10,492","68,448","±9,023","85,840","±12,866",N,N,"41,427","±9,366"
16,PERCENT IMPUTED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Household income in the past 12 months,44.9%,(X),(X),(X),(X),(X),(X),(X),41.4%,...,(X),(X),29.0%,(X),(X),(X),(X),(X),(X),(X)
18,Family income in the past 12 months,(X),(X),47.8%,(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),28.8%,(X),(X),(X),(X),(X)
19,Nonfamily income in the past 12 months,(X),(X),(X),(X),(X),(X),31.0%,(X),(X),...,23.7%,(X),(X),(X),(X),(X),(X),(X),25.2%,(X)

In [ ]:
dor_income_2020

,0,1,2,3,4,5,6,7,8,9,...,223,224,225,226,227,228,229,230,231,232
0,NaN,"Census Tract 901, Suffolk County, Massachusetts",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Census Tract 902, Suffolk County, Massachusetts",...,NaN,NaN,"Census Tract 1008, Suffolk County, Massachusetts",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Households,NaN,Families,NaN,Married-couple families,NaN,Nonfamily households,NaN,Households,...,Nonfamily households,NaN,Households,NaN,Families,NaN,Married-couple families,NaN,Nonfamily households,NaN
2,Label,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,...,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error
3,Total,"2,002",±331,"1,331",±331,494,±255,671,±133,730,...,769,±154,"2,854",±350,"1,526",±315,926,±236,"1,328",±303
4,"Less than $10,000",18.8%,±11.9,21.1%,±17.3,40.5%,±41.4,14.8%,±9.4,24.8%,...,10.0%,±6.2,7.8%,±4.4,6.7%,±6.2,9.0%,±9.8,10.5%,±7.0
5,"$10,000 to $14,999",6.1%,±4.0,6.9%,±5.7,0.0%,±7.8,4.6%,±3.9,9.9%,...,4.4%,±3.4,5.0%,±3.7,0.0%,±2.6,0.0%,±4.2,10.8%,±7.7
6,"$15,000 to $24,999",14.8%,±6.4,12.2%,±7.9,17.0%,±20.1,23.5%,±12.1,10.4%,...,4.9%,±6.1,2.9%,±3.1,1.2%,±2.1,0.0%,±4.2,4.9%,±6.2
7,"$25,000 to $34,999",17.6%,±6.3,17.1%,±8.3,3.4%,±4.7,19.2%,±10.1,13.8%,...,6.6%,±5.4,8.6%,±5.3,6.4%,±4.5,3.8%,±4.2,11.1%,±9.6
8,"$35,000 to $49,999",7.0%,±3.6,9.0%,±5.6,2.6%,±4.4,4.0%,±4.5,10.1%,...,8.7%,±7.0,12.6%,±7.0,4.3%,±4.4,3.8%,±4.4,22.2%,±13.9
9,"$50,000 to $74,999",14.1%,±5.3,12.2%,±7.2,11.5%,±12.9,16.1%,±10.4,17.9%,...,17.6%,±10.5,10.8%,±6.5,8.5%,±8.5,1.4%,±2.4,12.0%,±9.5
10,"$75,000 to $99,999",8.8%,±4.6,12.1%,±7.1,11.9%,±13.2,2.2%,±3.6,6.7%,...,13.9%,±8.8,8.3%,±4.5,12.6%,±7.4,14.9%,±10.4,5.0%,±4.1
11,"$100,000 to $149,999",10.6%,±4.7,8.1%,±5.7,9.7%,±9.0,14.5%,±8.4,5.9%,...,18.1%,±9.8,19.8%,±6.8,27.9%,±10.0,26.3%,±11.6,10.5%,±5.9
12,"$150,000 to $199,999",1.6%,±1.7,0.3%,±0.5,0.8%,±1.5,1.0%,±1.9,0.0%,...,10.4%,±6.8,12.2%,±4.1,18.2%,±9.5,17.3%,±11.4,8.7%,±6.5
13,"$200,000 or more",0.6%,±0.9,0.9%,±1.4,2.4%,±4.3,0.0%,±5.8,0.4%,...,5.3%,±6.4,12.0%,±6.1,14.3%,±8.2,23.5%,±12.3,4.3%,±3.7
14,Median income (dollars),"33,069","±3,693","33,139","±8,009",-,**,"31,276","±6,619","28,462",...,"70,880","±18,908","82,054","±25,896","109,722","±25,051","133,682","±20,000","43,676","±9,349"
15,Mean income (dollars),"50,010","±10,252","49,583","±14,852",N,N,"45,368","±8,747","37,359",...,"91,149","±27,883","102,210","±14,246","125,962","±18,342",N,N,"66,327","±14,320"
16,PERCENT ALLOCATED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Household income in the past 12 months,56.7%,(X),(X),(X),(X),(X),(X),(X),30.1%,...,(X),(X),33.4%,(X),(X),(X),(X),(X),(X),(X)
18,Family income in the past 12 months,(X),(X),66.9%,(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),36.7%,(X),(X),(X),(X),(X)
19,Nonfamily income in the past 12 months,(X),(X),(X),(X),(X),(X),35.9%,(X),(X),...,30.7%,(X),(X),(X),(X),(X),(X),(X),29.6%,(X)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,127,128,129,130,131,132,133,134,135,136
0,NaN,"Census Tract 708.01, Suffolk County, Massachus...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Census Tract 801, Suffolk County, Massachusetts",...,NaN,NaN,"Census Tract 9803, Suffolk County, Massachusetts",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Households,NaN,Families,NaN,Married-couple families,NaN,Nonfamily households,NaN,Households,...,Nonfamily households,NaN,Households,NaN,Families,NaN,Married-couple families,NaN,Nonfamily households,NaN
2,Label,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,...,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error,Estimate,Margin of Error
3,Total,559,±133,92,±70,81,±67,467,±149,709,...,316,±129,0,±13,0,±13,0,±13,0,±13
4,"Less than $10,000",0.0%,±6.9,0.0%,±33.6,0.0%,±36.4,0.0%,±8.2,16.1%,...,24.1%,±16.3,-,**,-,**,-,**,-,**
5,"$10,000 to $14,999",9.1%,±12.9,0.0%,±33.6,0.0%,±36.4,10.9%,±15.5,5.6%,...,12.7%,±20.0,-,**,-,**,-,**,-,**
6,"$15,000 to $24,999",7.5%,±8.6,28.3%,±42.9,32.1%,±48.7,3.4%,±5.8,16.4%,...,15.2%,±11.2,-,**,-,**,-,**,-,**
7,"$25,000 to $34,999",3.9%,±6.8,0.0%,±33.6,0.0%,±36.4,4.7%,±8.3,10.4%,...,7.0%,±8.2,-,**,-,**,-,**,-,**
8,"$35,000 to $49,999",18.8%,±15.3,0.0%,±33.6,0.0%,±36.4,22.5%,±18.2,16.6%,...,23.4%,±19.9,-,**,-,**,-,**,-,**
9,"$50,000 to $74,999",3.8%,±5.1,0.0%,±33.6,0.0%,±36.4,4.5%,±6.4,11.0%,...,7.3%,±6.6,-,**,-,**,-,**,-,**
10,"$75,000 to $99,999",3.9%,±6.6,0.0%,±33.6,0.0%,±36.4,4.7%,±7.9,2.7%,...,1.9%,±2.8,-,**,-,**,-,**,-,**
11,"$100,000 to $149,999",4.1%,±5.1,0.0%,±33.6,0.0%,±36.4,4.9%,±6.4,8.3%,...,4.4%,±6.9,-,**,-,**,-,**,-,**
12,"$150,000 to $199,999",18.1%,±14.8,21.7%,±34.1,24.7%,±40.0,17.3%,±15.9,5.9%,...,4.1%,±6.8,-,**,-,**,-,**,-,**
13,"$200,000 or more",30.8%,±18.0,50.0%,±46.9,43.2%,±53.5,27.0%,±17.7,6.9%,...,0.0%,±11.9,-,**,-,**,-,**,-,**
14,Median income (dollars),-,**,"225,000","±204,431",-,**,-,**,"42,563",...,-,**,-,**,-,**,-,**,-,**
15,Mean income (dollars),"160,064","±55,998","279,040","±197,663",N,N,"128,977","±42,024","60,228",...,"37,395","±13,582",-,**,-,**,-,**,-,**
16,PERCENT ALLOCATED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Household income in the past 12 months,26.8%,(X),(X),(X),(X),(X),(X),(X),29.3%,...,(X),(X),-,(X),(X),(X),(X),(X),(X),(X)
18,Family income in the past 12 months,(X),(X),0.0%,(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),-,(X),(X),(X),(X),(X)
19,Nonfamily income in the past 12 months,(X),(X),(X),(X),(X),(X),32.1%,(X),(X),...,44.3%,(X),(X),(X),(X),(X),(X),(X),-,(X)

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/DS project/ACSST5Y2021.S1901-2023-10-21T013115.xlsx', sheet_name=1, header=None)  # Reading the second sheet and specifying no header

# Now, let's merge the first three rows into one row for column names.
# You can do this by selecting the first three rows and combining them into a single header row.
# You can use the `.iloc` method to select rows by index.

header = df.iloc[0:3].apply(lambda x: '_'.join(x.astype(str)), axis=0)
# Convert the values to strings using `astype(str)` before joining them.

# Now, assign the merged header row as the column names and skip the first three rows.
df.columns = header
df = df[3:]
df = df.set_index(df.columns[0])
df = df.transpose()

FileNotFoundError: ignored

In [ ]:
df

nan_nan_Label,Total,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months
"Census Tract 708.01, Suffolk County, Massachusetts_Households_Estimate",559,0.0%,9.1%,7.5%,3.9%,18.8%,3.8%,3.9%,4.1%,18.1%,30.8%,-,"160,064",NaN,26.8%,(X),(X)
nan_nan_Margin of Error,±133,±6.9,±12.9,±8.6,±6.8,±15.3,±5.1,±6.6,±5.1,±14.8,±18.0,**,"±55,998",NaN,(X),(X),(X)
nan_Families_Estimate,92,0.0%,0.0%,28.3%,0.0%,0.0%,0.0%,0.0%,0.0%,21.7%,50.0%,"225,000","279,040",NaN,(X),0.0%,(X)
nan_nan_Margin of Error,±70,±33.6,±33.6,±42.9,±33.6,±33.6,±33.6,±33.6,±33.6,±34.1,±46.9,"±204,431","±197,663",NaN,(X),(X),(X)
nan_Married-couple families_Estimate,81,0.0%,0.0%,32.1%,0.0%,0.0%,0.0%,0.0%,0.0%,24.7%,43.2%,-,N,NaN,(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nan_nan_Margin of Error,±13,**,**,**,**,**,**,**,**,**,**,**,**,NaN,(X),(X),(X)
nan_Married-couple families_Estimate,0,-,-,-,-,-,-,-,-,-,-,-,-,NaN,(X),(X),(X)
nan_nan_Margin of Error,±13,**,**,**,**,**,**,**,**,**,**,**,**,NaN,(X),(X),(X)
nan_Nonfamily households_Estimate,0,-,-,-,-,-,-,-,-,-,-,-,-,NaN,(X),(X),-
nan_nan_Margin of Error,±13,**,**,**,**,**,**,**,**,**,**,**,**,NaN,(X),(X),(X)

In [ ]:
df= df[df.reset_index().index % 2 == 0]

In [ ]:
new_df = df.iloc[:4].copy()
# Add a new column named "year" with the value 2021
year = 2021
#new_df['year'] = year
 # Replace with year data
new_df.insert(0, 'year', year)

In [ ]:
new_df

nan_nan_Label,year,Total,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months
"Census Tract 708.01, Suffolk County, Massachusetts_Households_Estimate",2021,559,0.0%,9.1%,7.5%,3.9%,18.8%,3.8%,3.9%,4.1%,18.1%,30.8%,-,"160,064",NaN,26.8%,(X),(X)
nan_Families_Estimate,2021,92,0.0%,0.0%,28.3%,0.0%,0.0%,0.0%,0.0%,0.0%,21.7%,50.0%,"225,000","279,040",NaN,(X),0.0%,(X)
nan_Married-couple families_Estimate,2021,81,0.0%,0.0%,32.1%,0.0%,0.0%,0.0%,0.0%,0.0%,24.7%,43.2%,-,N,NaN,(X),(X),(X)
nan_Nonfamily households_Estimate,2021,467,0.0%,10.9%,3.4%,4.7%,22.5%,4.5%,4.7%,4.9%,17.3%,27.0%,-,"128,977",NaN,(X),(X),32.1%

In [ ]:
new_df = new_df.reset_index()

In [ ]:
if isinstance(new_df.iat[0, 0], str) and len(new_df.iat[0, 0]) > 19:
    # Modify the first cell value by slicing it to retain only the last 19 characters
    new_df.iat[0, 0] = new_df.iat[0, 0][-23:]

In [ ]:
new_df = new_df.rename(columns={'index': 'estimate_type'})
new_df['estimate_type'] = new_df['estimate_type'].str[4:]
new_df

nan_nan_Label,estimate_type,year,Total,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months
0,Households_Estimate,2021,559,0.0%,9.1%,7.5%,3.9%,18.8%,3.8%,3.9%,4.1%,18.1%,30.8%,-,"160,064",NaN,26.8%,(X),(X)
1,Families_Estimate,2021,92,0.0%,0.0%,28.3%,0.0%,0.0%,0.0%,0.0%,0.0%,21.7%,50.0%,"225,000","279,040",NaN,(X),0.0%,(X)
2,Married-couple families_Estimate,2021,81,0.0%,0.0%,32.1%,0.0%,0.0%,0.0%,0.0%,0.0%,24.7%,43.2%,-,N,NaN,(X),(X),(X)
3,Nonfamily households_Estimate,2021,467,0.0%,10.9%,3.4%,4.7%,22.5%,4.5%,4.7%,4.9%,17.3%,27.0%,-,"128,977",NaN,(X),(X),32.1%

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/DS project/ACSST5Y' + str(year) + '.S1901-2023-10-21T033545.xlsx',
                   sheet_name=1, header=None)
# Now, let's merge the first three rows into one row for column names.
# You can do this by selecting the first three rows and combining them into a single header row.
# You can use the `.iloc` method to select rows by index.

header = df.iloc[0:3].apply(lambda x: '_'.join(x.astype(str)), axis=0)
# Convert the values to strings using `astype(str)` before joining them.

# Now, assign the merged header row as the column names and skip the first three rows.
df.columns = header
df = df[3:]
df = df.set_index(df.columns[0])
df = df.transpose()
df= df[df.reset_index().index % 2 == 0]

new_df = df.iloc[:4].copy()
# Add a new column named "year" with the value 2021
year = 2021
#new_df['year'] = year
 # Replace with year data
new_df.insert(0, 'year', year)
new_df = new_df.reset_index()

if isinstance(new_df.iat[0, 0], str) and len(new_df.iat[0, 0]) > 19:
    # Modify the first cell value by slicing it to retain only the last 19 characters
    new_df.iat[0, 0] = new_df.iat[0, 0][-23:]

new_df = new_df.rename(columns={'index': 'estimate_type'})
new_df['estimate_type'] = new_df['estimate_type'].str[4:]
new_df

## Create dataframe

In [ ]:
years = [year for year in range(2021, 2009, -1)]
years

[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010]

In [ ]:
def process_excel_file(year, excel_path):
    df = pd.read_excel(excel_path, sheet_name=1, header=None)

    header = df.iloc[0:3].apply(lambda x: '_'.join(x.astype(str)), axis=0)
    df.columns = header
    df = df[3:]

    df = df.set_index(df.columns[0])
    df = df.transpose()

    df = df[df.reset_index().index % 2 == 0]

    new_df = df.iloc[:4].copy()
    new_df.insert(0, 'year', year)
    new_df = new_df.reset_index()

    if isinstance(new_df.iat[0, 0], str) and len(new_df.iat[0, 0]) > 23:
        new_df.iat[0, 0] = new_df.iat[0, 0][-23:]

    new_df = new_df.rename(columns={'index': 'estimate_type'})
    new_df['estimate_type'] = new_df['estimate_type'].str[4:]

    return new_df

##considering make another function

In [ ]:
years = [year for year in range(2021, 2009, -1)]
years

[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010]

In [ ]:
from re import I
def process_excel_file(year, excel_path, list_index):
    df = pd.read_excel(excel_path, sheet_name=1, header=None)

    header = df.iloc[0:3].apply(lambda x: '_'.join(x.astype(str)), axis=0)
    df.columns = header
    df = df[3:]

    df = df.set_index(df.columns[0])
    df = df.transpose()

    df = df[df.reset_index().index % 2 == 0]

    # Calculate the starting and ending row indices based on the list_index
    start_row = list_index * 4
    end_row = (list_index + 1) * 4

    new_df = df.iloc[start_row:end_row].copy()
    new_df.insert(0, 'year', year)
    new_df = new_df.reset_index()

    if isinstance(new_df.iat[0, 0], str) and len(new_df.iat[0, 0]) > 23:
        new_df.iat[0, 0] = new_df.iat[0, 0][-23:]

    new_df = new_df.rename(columns={'index': 'estimate_type'})
    new_df['estimate_type'] = new_df['estimate_type'].str[4:]
    new_df['Total'] = pd.to_numeric(new_df['Total'].str.replace(',', ''), errors='coerce').astype(float)

    return new_df

In [ ]:
list_of_indices = ["901", "902", "903", "907",
                   "90901", "91001",
                   "911", "912", "913", "914", "915", "916", "917", "918", "919", "920",
                   "92101", "922", "923", "924",
                   "1001", "1002", "1003", "1004", "1005", "100601", "100603", "1007", "1008"]



  #['70801', '70901', '801', '803', '80401', '805', '80601',
                   #'81302', '814', '815', '817', '818', '819', '820', '821', '904','906', '9803']

In [ ]:
len(list_of_indices)

29

In [ ]:
#this loop makes use of the function process_excel_file() to make different years of dataframe for each census tract
for index in list_of_indices:
    for year in years:
        excel_file_path = f'/content/drive/MyDrive/DS project/Dorchester_income/ACSST5Y{year}.xlsx'
        variable_name = f'ct{index}_{year}'

        # Determine the list_index based on the current index
        list_index = list_of_indices.index(index)

        # Call the function and assign the result to the variable
        globals()[variable_name] = process_excel_file(year, excel_file_path, list_index)

In [ ]:
#this for loop generates the concated dataframe

for index in list_of_indices:
    concatenated_dfs = [globals()[f'ct{index}_2021']]  # Start with the 2021 DataFrame

    for year in years[1:]:
        variable_name = f'ct{index}_{year}'
        if not globals()[variable_name].empty:
            concatenated_dfs.append(globals()[variable_name])

    # Concatenate all DataFrames for the current index
    globals()[f'ct{index}'] = pd.concat(concatenated_dfs, ignore_index=True)

In [ ]:
ct1001

nan_nan_Label,estimate_type,year,Total,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months,PERCENT IMPUTED
0,Households_Estimate,2021,2124.0,12.9%,10.5%,5.7%,18.5%,10.9%,16.4%,4.2%,7.5%,7.9%,5.4%,"36,471","62,289",NaN,43.6%,(X),(X),NaN
1,Families_Estimate,2021,1639.0,5.7%,5.7%,3.2%,24.8%,14.2%,16.4%,5.5%,11.6%,7.1%,5.9%,"41,414","69,180",NaN,(X),43.7%,(X),NaN
2,Married-couple families_Estimate,2021,581.0,0.0%,0.0%,2.1%,7.4%,19.8%,18.2%,6.5%,24.8%,12.7%,8.4%,"84,609",N,NaN,(X),(X),(X),NaN
3,Nonfamily households_Estimate,2021,485.0,36.9%,26.8%,14.4%,4.9%,0.0%,8.9%,0.0%,4.3%,0.0%,3.7%,"13,401","31,374",NaN,(X),(X),40.4%,NaN
4,Households_Estimate,2020,2100.0,15.3%,9.3%,13.0%,15.1%,11.1%,10.0%,7.5%,12.0%,2.8%,3.8%,"31,071","53,702",NaN,39.7%,(X),(X),NaN
5,Families_Estimate,2020,1644.0,8.6%,4.7%,14.0%,20.4%,12.2%,10.5%,8.2%,14.2%,2.4%,4.8%,"35,969","60,033",NaN,(X),41.6%,(X),NaN
6,Married-couple families_Estimate,2020,507.0,0.0%,1.8%,2.0%,11.6%,18.7%,6.7%,11.0%,29.0%,7.9%,11.2%,"96,313",N,NaN,(X),(X),(X),NaN
7,Nonfamily households_Estimate,2020,456.0,39.7%,25.9%,9.4%,3.9%,7.5%,0.2%,9.4%,3.9%,0.0%,0.0%,"11,546","24,584",NaN,(X),(X),29.2%,NaN
8,Households_Estimate,2019,2203.0,19.9%,11.7%,12.6%,11.9%,12.5%,9.8%,6.5%,10.3%,2.4%,2.4%,"28,659","48,088",NaN,37.7%,(X),(X),NaN
9,Families_Estimate,2019,1578.0,10.8%,8.2%,12.8%,17.6%,13.6%,9.6%,8.1%,13.8%,2.2%,3.4%,"35,272","56,651",NaN,(X),42.9%,(X),NaN
10,Married-couple families_Estimate,2019,463.0,0.0%,1.7%,6.5%,20.7%,20.7%,0.0%,11.4%,26.8%,7.3%,4.8%,"77,734",N,NaN,(X),(X),(X),NaN
11,Nonfamily households_Estimate,2019,625.0,42.9%,20.5%,13.4%,6.6%,9.3%,1.4%,3.2%,2.7%,0.0%,0.0%,"11,503","20,580",NaN,(X),(X),24.6%,NaN
12,Households_Estimate,2018,2201.0,18.5%,12.9%,11.0%,13.0%,9.9%,10.5%,5.4%,10.2%,6.1%,2.5%,"29,483","52,459",NaN,45.1%,(X),(X),NaN
13,Families_Estimate,2018,1570.0,11.1%,8.4%,12.0%,14.4%,12.4%,11.5%,5.4%,13.7%,9.4%,1.7%,"37,692","62,450",NaN,(X),51.8%,(X),NaN
14,Married-couple families_Estimate,2018,518.0,0.0%,1.5%,10.8%,16.8%,15.4%,4.6%,8.3%,19.3%,18.1%,5.0%,"78,333",N,NaN,(X),(X),(X),NaN
15,Nonfamily households_Estimate,2018,631.0,36.9%,25.5%,8.4%,9.7%,5.7%,6.0%,5.4%,2.4%,0.0%,0.0%,"12,292","23,597",NaN,(X),(X),28.4%,NaN
16,Households_Estimate,2017,2191.0,21.7%,13.1%,12.4%,10.5%,10.7%,11.6%,5.6%,9.4%,3.5%,1.6%,"27,750","46,834",NaN,43.2%,(X),(X),NaN
17,Families_Estimate,2017,1526.0,13.2%,11.3%,11.5%,10.7%,15.9%,11.5%,6.4%,12.1%,6.7%,0.5%,"37,356","56,153",NaN,(X),49.3%,(X),NaN
18,Married-couple families_Estimate,2017,433.0,0.7%,3.7%,12.0%,10.9%,20.1%,4.8%,12.9%,15.2%,17.8%,1.8%,"61,369",N,NaN,(X),(X),(X),NaN
19,Nonfamily households_Estimate,2017,665.0,41.1%,21.2%,11.9%,9.8%,4.2%,9.6%,2.3%,0.0%,0.0%,0.0%,"11,792","20,103",NaN,(X),(X),26.8%,NaN
20,Households_Estimate,2016,2010.0,19.5%,13.9%,11.5%,13.1%,10.4%,14.5%,4.9%,8.9%,2.6%,0.7%,"28,279","43,782",NaN,43.5%,(X),(X),NaN
21,Families_Estimate,2016,1355.0,13.4%,10.6%,10.0%,15.5%,15.7%,14.2%,4.1%,11.7%,3.9%,1.0%,"35,574","51,535",NaN,(X),49.6%,(X),NaN
22,Married-couple families_Estimate,2016,370.0,0.0%,9.2%,8.6%,10.0%,24.3%,10.3%,2.4%,17.0%,14.3%,3.8%,"44,692",N,NaN,(X),(X),(X),NaN
23,Nonfamily households_Estimate,2016,655.0,32.2%,24.7%,12.2%,9.6%,5.5%,12.5%,3.2%,0.0%,0.0%,0.0%,"12,407","22,449",NaN,(X),(X),28.4%,NaN
24,Households_Estimate,2015,2023.0,22.1%,16.2%,11.1%,10.1%,8.8%,13.5%,5.7%,7.7%,3.0%,1.8%,"25,504","44,568",NaN,43.7%,(X),(X),NaN
25,Families_Estimate,2015,1328.0,14.3%,13.1%,7.9%,15.8%,11.4%,15.1%,5.5%,9.7%,4.5%,2.7%,"34,643","54,745",NaN,(X),49.5%,(X),NaN
26,Married-couple families_Estimate,2015,416.0,0.0%,7.9%,9.1%,10.6%,15.1%,14.7%,5.3%,14.2%,14.4%,8.7%,(X),N,NaN,(X),(X),(X),NaN
27,Nonfamily households_Estimate,2015,695.0,37.1%,26.5%,14.5%,4.0%,7.5%,6.9%,3.5%,0.0%,0.0%,0.0%,"11,492","18,821",NaN,(X),(X),29.9%,NaN
28,Households_Estimate,2014,1976.0,20.9%,13.5%,12.2%,9.8%,10.6%,15.0%,5.8%,8.9%,2.9%,0.4%,"28,671","43,711",NaN,43.0%,(X),(X),NaN
29,Families_Estimate,2014,1369.0,14.8%,9.9%,10.7%,15.1%,11.1%,17.1%,5.5%,11.0%,4.2%,0.6%,"34,807","50,949",NaN,(X),44.6%,(X),NaN
30,Married-couple families_Estimate,2014,403.0,3.7%,9.4%,11.7%,9.9%,7.9%,21.8%,2.7%,22.8%,7.9%,2.0%,"59,632",N,NaN,(X),(X),(X),NaN
31,Nonfamily households_Estimate,2014,607.0,37.9%,24.4%,12.9%,3.5%,9.7%,6.4%,5.3%,0.0%,0.0%,0.0%,"11,382","20,623",NaN,(X),(X),35.3%,NaN
32,Households_Estimate,2013,1965.0,23.1%,13.1%,13.9%,10.6%,8.9%,13.2%,5.4%,10.4%,1.0%,0.5%,"24,886","40,835",NaN,38.5%,(X),(X),NaN
33,Families_Estimate,2013,1426.0,18.7%,10.6%,12.8%,15.8%,8.2%,15.6%,5.8%,10.7%,1.4%,0.6%,"32,566","44,635",NaN,(X),34.2%,(X),NaN
34,Married-couple families_Estimate,2013,352.0,7.7%,10.2%,2.8%,6.3%,13.1%,19.6%,4.0%,33.8%,0.0%,2.6%,"69,167",N,NaN,(X),(X),(X),NaN
35,Nonfamily households_Estimate,2013,539.0,42.9%,19.7%,12.6%,5.2%,10.8%,0.0%,3.0%,5.9%,0.0%,0.0%,"11,234","23,707",NaN,(X),(X),39.9%,NaN
36,Households_Estimate,2012,1878.0,22.5%,12.2%,12.2%,10.7%,10.2%,15.0%,6.9%,7.0%,1.8%,1.5%,"27,840","42,515",NaN,37.8%,(X),(X),NaN
37,Families_Estimate,2012,1327.0,16.5%,8.2%,13.3%,14.2%,7.2%,20.4%,7.5%,7.9%,2.6%,2.1%,"33,729","49,216",NaN,(X),34.5%,(X),NaN
38,Married-couple families_Estimate,2012,405.0,6.4%,6.2%,5.7%,7.7%,9.1%,25.4%,9.6%,23.0%,0.0%,6.9%,"68,079",N,NaN,(X),(X),(X),NaN
39,Nonfamily households_Estimate,2012,551.0,40.7%,21.8%,9.4%,4.2%,15.1%,0.0%,4.2%,4.7%,0.0%,0.0%,"11,288","23,790",NaN,(X),(X),40.5%,NaN
40,Households_Estimate,2011,1737.0,24.1%,11.7%,15.8%,12.9%,12.6%,12.1%,3.1%,3.6%,4.0%,0.0%,"22,375","37,171",NaN,40.1%,(X),(X),NaN
41,Families_Estimate,2011,1312.0,19.2%,10.1%,15.8%,16.4%,10.4%,16.1%,4.0%,2.7%,5.3%,0.0%,"28,261","41,330",NaN,(X),38.1%,(X),NaN
42,Married-couple families_Estimate,2011,332.0,8.1%,3.6%,9.3%,8.1%,13.9%,31.0%,7.5%,10.8%,7.5%,0.0%,"65,417",N,NaN,(X),(X),(X),NaN
43,Nonfamily households_Estimate,2011,425.0,49.6%,16.5%,10.4%,6.1%,10.6%,0.0%,0.5%,6.4%,0.0%,0.0%,"10,078","20,910",NaN,(X),(X),34.6%,NaN
44,Households_Estimate,2010,1691.0,26.2%,8.1%,13.1%,11.7%,13.0%,11.5%,3.8%,8.2%,4.4%,0.0%,"26,007","41,877",NaN,41.6%,(X),(X),NaN
45,Families_Estimate,2010,1342.0,20.1%,6.8%,14.1%,13.3%,15.6%,14.5%,3.9%,7.1%,4.7%,0.0%,"30,294","44,965",NaN,(X),40.8%,(X),NaN
46,Married-couple families_Estimate,2010,386.0,9.6%,0.0%,8.3%,3.6%,12.7%,28.0%,9.3%,21.8%,6.7%,0.0%,"67,432",N,NaN,(X),(X),(X),NaN
47,Nonfamily households_Estimate,2010,349.0,60.5%,13.2%,3.2%,5.7%,8.9%,0.0%,1.1%,7.4%,0.0%,0.0%,"9,078","21,103",NaN,(X),(X),36.4%,NaN

In [ ]:
def convert_percentage_to_float_with_symbol(percentage_str):
    if isinstance(percentage_str, str):
        cleaned_str = percentage_str.replace('%', '').replace('-', '')
        try:
            return float(cleaned_str) / 100.0
        except ValueError:
            # Handle cases where the cleaned string couldn't be converted to float
            return None
    else:
        return percentage_str


def convert_column_to_float(df):
  columns_to_convert = df.columns[3:13]

  for col in columns_to_convert:
    df[col] = df[col].apply(convert_percentage_to_float_with_symbol)
    df[col] = df[col] * df['Total']
  # Convert the selected columns to float64
  #df[columns_to_convert] = df[columns_to_convert].astype(float)
  return df

In [ ]:
#processing the concated dataframe, (strip%and, mutliplied by total)
for index in list_of_indices:
  dataframe_name = f'ct{index}'
  globals()[dataframe_name]  = convert_column_to_float(globals()[dataframe_name])

In [ ]:
for index in list_of_indices:
  dataframe_name = f'ct{index}'
  globals()[dataframe_name]  = globals()[dataframe_name][globals()[dataframe_name]['estimate_type']=='Households_Estimate']

In [ ]:
#calculating income difference
for index in list_of_indices:
    df = f'ct{index}'

    # Clean the 'Median income (dollars)' column by removing commas and dashes
    globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].str.replace(',', '').str.replace('-', '')
    # Clean the 'Mean income..
    globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].str.replace(',', '').str.replace('-', '')

    # Convert the cleaned column to float, handling non-numeric values
    def convert_to_float(value):
        try:
            return float(value)
        except (ValueError, TypeError):
            return None

    globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].apply(convert_to_float)
    globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].apply(convert_to_float)

    # Calculate the 'median_income_difference' column
    globals()[df]['median_income_difference'] = ((globals()[df]['Median income (dollars)'] - globals()[df]['Median income (dollars)'].shift(-1)) / globals()[df]['Median income (dollars)'].shift(-1))
    globals()[df]['mean_income_difference'] = ((globals()[df]['Mean income (dollars)'] - globals()[df]['Mean income (dollars)'].shift(-1)) / globals()[df]['Mean income (dollars)'].shift(-1))

<ipython-input-14-1f052636bfbd>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['median_income_difference'] = ((globals()[df]['Median income (dollars)'] - globals()[df]['Median income (dollars)'].shift(-1)) / globals()[df]['Median income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['mean_income_difference'] = ((globals()[df]['Mean income (dollars)'] - globals()[df]['Mean income (dollars)'].shift(-1)) / globals()[df]['Mean income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['median_income_difference'] = ((globals()[df]['Median income (dollars)'] - globals()[df]['Median income (dollars)'].shift(-1)) / globals()[df]['Median income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['mean_income_difference'] = ((globals()[df]['Mean income (dollars)'] - globals()[df]['Mean income (dollars)'].shift(-1)) / globals()[df]['Mean income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['median_income_difference'] = ((globals()[df]['Median income (dollars)'] - globals()[df]['Median income (dollars)'].shift(-1)) / globals()[df]['Median income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['mean_income_difference'] = ((globals()[df]['Mean income (dollars)'] - globals()[df]['Mean income (dollars)'].shift(-1)) / globals()[df]['Mean income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['median_income_difference'] = ((globals()[df]['Median income (dollars)'] - globals()[df]['Median income (dollars)'].shift(-1)) / globals()[df]['Median income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['mean_income_difference'] = ((globals()[df]['Mean income (dollars)'] - globals()[df]['Mean income (dollars)'].shift(-1)) / globals()[df]['Mean income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['median_income_difference'] = ((globals()[df]['Median income (dollars)'] - globals()[df]['Median income (dollars)'].shift(-1)) / globals()[df]['Median income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['mean_income_difference'] = ((globals()[df]['Mean income (dollars)'] - globals()[df]['Mean income (dollars)'].shift(-1)) / globals()[df]['Mean income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['median_income_difference'] = ((globals()[df]['Median income (dollars)'] - globals()[df]['Median income (dollars)'].shift(-1)) / globals()[df]['Median income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['mean_income_difference'] = ((globals()[df]['Mean income (dollars)'] - globals()[df]['Mean income (dollars)'].shift(-1)) / globals()[df]['Mean income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].str.replace(',', '').str.replace('-', '')
<ipython-input-14-1f052636bfbd>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Mean income (dollars)'] = globals()[df]['Mean income (dollars)'].apply(convert_to_float)
<ipython-input-14-1f052636bfbd>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['median_income_difference'] = ((globals()[df]['Median income (dollars)'] - globals()[df]['Median income (dollars)'].shift(-1)) / globals()[df]['Median income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['mean_income_difference'] = ((globals()[df]['Mean income (dollars)'] - globals()[df]['Mean income (dollars)'].shift(-1)) / globals()[df]['Mean income (dollars)'].shift(-1))
<ipython-input-14-1f052636bfbd>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[df]['Median income (dollars)'] = globals()[df]['Median income (dollars)'].str.replace(',', '').str.replace('-', '')

In [ ]:
# adding census tract identifier column
for index in list_of_indices:
  dataframe_name = f'ct{index}'
  globals()[dataframe_name]['census_tract']  = index

<ipython-input-15-e561fdeb9973>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  globals()[dataframe_name]['census_tract']  = index

In [ ]:

list_of_indices
# Create a list of DataFrames
concatenated_df = [globals()[f'ct{index}'] for index in list_of_indices]

# Initialize an empty DataFrame to store the concatenated result
dorchester_income = pd.DataFrame()

# Concatenate the DataFrames in the list
for df in concatenated_df:
    dorchester_income = pd.concat([dorchester_income, df], ignore_index=True)

In [ ]:
dorchester_income.columns

Index(['estimate_type', 'year', 'Total', 'Less than $10,000',
       '$10,000 to $14,999', '$15,000 to $24,999', '$25,000 to $34,999',
       '$35,000 to $49,999', '$50,000 to $74,999', '$75,000 to $99,999',
       '$100,000 to $149,999', '$150,000 to $199,999', '$200,000 or more',
       'Median income (dollars)', 'Mean income (dollars)', 'PERCENT ALLOCATED',
       'Household income in the past 12 months',
       'Family income in the past 12 months',
       'Nonfamily income in the past 12 months', 'PERCENT IMPUTED',
       'median_income_difference', 'mean_income_difference', 'census_tract'],
      dtype='object', name='nan_nan_Label')

In [ ]:
income_dorchester_result_df = dorchester_income[['year', 'Total', 'Median income (dollars)', 'Mean income (dollars)','median_income_difference',
                                                 'mean_income_difference', 'census_tract']]

#income_dorchester_result_df = income_dorchester_result_df[income_dorchester_result_df['census_tract'] != 9803]
income_dorchester_result_df = income_dorchester_result_df.reset_index(drop=True)

In [ ]:
income_dorchester_result_df

nan_nan_Label,year,Total,Median income (dollars),Mean income (dollars),median_income_difference,mean_income_difference,census_tract
0,2021,1980.0,33652.0,55348.0,0.017630,0.106739,901
1,2020,2002.0,33069.0,50010.0,-0.032929,-0.105287,901
2,2019,1822.0,34195.0,55895.0,0.045655,0.185598,901
3,2018,1815.0,32702.0,47145.0,0.079880,0.076542,901
4,2017,1803.0,30283.0,43793.0,0.067731,0.064384,901
...,...,...,...,...,...,...,...
343,2014,2660.0,65762.0,73137.0,-0.043183,-0.014764,1008
344,2013,2598.0,68730.0,74233.0,0.022905,-0.014680,1008
345,2012,2580.0,67191.0,75339.0,0.104879,0.054297,1008
346,2011,2521.0,60813.0,71459.0,0.070651,0.043990,1008
347,2010,2376.0,56800.0,68448.0,NaN,NaN,1008

In [ ]:
income_dorchester_result_df.to_csv('/content/drive/MyDrive/DS project/Dorchester_income/dorchester_income.csv')

In [ ]:
ct1001

nan_nan_Label,estimate_type,year,Total,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999",...,"$200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months,PERCENT IMPUTED,median_income_difference,census_tract
0,Households_Estimate,2021,2124.0,273.996,223.020,121.068,392.940,231.516,348.336,89.208,...,114.696,36471.0,"62,289",NaN,43.6%,(X),(X),NaN,0.173796,1001
4,Households_Estimate,2020,2100.0,321.300,195.300,273.000,317.100,233.100,210.000,157.500,...,79.800,31071.0,"53,702",NaN,39.7%,(X),(X),NaN,0.084162,1001
8,Households_Estimate,2019,2203.0,438.397,257.751,277.578,262.157,275.375,215.894,143.195,...,52.872,28659.0,"48,088",NaN,37.7%,(X),(X),NaN,-0.027948,1001
12,Households_Estimate,2018,2201.0,407.185,283.929,242.110,286.130,217.899,231.105,118.854,...,55.025,29483.0,"52,459",NaN,45.1%,(X),(X),NaN,0.062450,1001
16,Households_Estimate,2017,2191.0,475.447,287.021,271.684,230.055,234.437,254.156,122.696,...,35.056,27750.0,"46,834",NaN,43.2%,(X),(X),NaN,-0.018706,1001
20,Households_Estimate,2016,2010.0,391.950,279.390,231.150,263.310,209.040,291.450,98.490,...,14.070,28279.0,"43,782",NaN,43.5%,(X),(X),NaN,0.108806,1001
24,Households_Estimate,2015,2023.0,447.083,327.726,224.553,204.323,178.024,273.105,115.311,...,36.414,25504.0,"44,568",NaN,43.7%,(X),(X),NaN,-0.110460,1001
28,Households_Estimate,2014,1976.0,412.984,266.760,241.072,193.648,209.456,296.400,114.608,...,7.904,28671.0,"43,711",NaN,43.0%,(X),(X),NaN,0.152094,1001
32,Households_Estimate,2013,1965.0,453.915,257.415,273.135,208.290,174.885,259.380,106.110,...,9.825,24886.0,"40,835",NaN,38.5%,(X),(X),NaN,-0.106106,1001
36,Households_Estimate,2012,1878.0,422.550,229.116,229.116,200.946,191.556,281.700,129.582,...,28.170,27840.0,"42,515",NaN,37.8%,(X),(X),NaN,0.244246,1001
40,Households_Estimate,2011,1737.0,418.617,203.229,274.446,224.073,218.862,210.177,53.847,...,0.000,22375.0,"37,171",NaN,40.1%,(X),(X),NaN,NaN,1001